global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: dashboard
    static_configs:
      - targets: ["dashboard:8080"]

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: mlflow
    metrics_path: /metrics
    static_configs:
      - targets: ["mlflow:5000"]
